### ISSUE TITLE
Support for Wasmer?

### ISSUE THREAD

**Issue by syrusakbary** [Pangoraw/Wasmtime.jl#4]
I just seen this library, great work!

Have you thought about supporting wasmer? I'd love to see an official Wasmer integration in Julia!

**Comment by Pangoraw** [comment]
Hi! I actually started with the hope having both Wasmtime and Wasmer inside the same package by wrapping only the wasm-c-api. But it turned out that not everything can be done with it so I decided to split the work in two packages like the [zigwasm packages](https://github.com/zigwasm). I have yet to create one for Wasmer, but the [implementation](https://github.com/Pangoraw/Wasmtime.jl/tree/9734aa965b2e9190640dda4668f76238913b4d7a/src/wasmer) was already started and can run wasi blobs and provide/call function to/from the sandbox via the wasm-c-api.

**Comment by Pangoraw** [comment]
I threw something together at [Wasmer.jl](https://github.com/Pangoraw/Wasmer.jl), however it cannot run WASI yet because of an unimplemented function in the wasm-c-api.

**Comment by syrusakbary** [comment]
That's great!

PS: What's the unimplemented function in the wasm-c-api? Could you create an issue in the wasmer repo so we can work on it? Thanks!

**Comment by syrusakbary** [comment]
Closing this, creating a WASI issue on the Wasmer.jl repo! Thanks for the awesome work
